spring:
  application:
    name: spring-bot
  threads:
    virtual:
      enabled: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  min-response-size: 30
  http2:
    enabled: true

download:
  max-file-size-mb: 30
  download-path: /tmp/

logging:
  level:
    root: INFO