spring:
  application:
    name: spring-bot
  threads:
    virtual:
      enabled: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  min-response-size: 30
  http2:
    enabled: true

download:
  max-file-size-mb: 30
  download-path: /tmp/

bot:
  name: '@tg_tiunchik_bot' #Not for code, just don't forget bot nickname
  token: ${BOT_TOKEN}
  allowed-users: tiunchik_maksim;Daniils_Loputevs;olose_tiunya;Free_Dog_Night

logging:
  level:
    root: INFO